/**
 * @fileoverview Icon mapping for dynamic icon loading
 * Only imports icons that are actually used in the application
 * to avoid importing the entire lucide-react library
 */

import {
  // Category icons (from User.js defaults)
  Briefcase,
  Gift,
  ArrowLeft,
  PlusCircle,
  Home,
  Zap,
  Droplet,
  Wifi,
  Phone,
  Fuel,
  Train,
  Wrench,
  ShoppingCart,
  Utensils,
  Heart,
  Music,
  Tv,
  Shirt,
  FileText,
  Landmark,
  MoreHorizontal,
  ArrowRightLeft,
  PiggyBank,
  // Common icons
  Tag,
  Wallet,
  Car,
  CreditCard,
  Building,
  Plane,
  Book,
  Coffee,
  Gamepad2,
  Baby,
  Dog,
  Cat,
  Flower2,
  Sun,
  Moon,
  Star,
  Flag,
  Bell,
  Clock,
  Calendar,
  Map,
  Globe,
  Camera,
  Image,
  Film,
  Headphones,
  Mic,
  Speaker,
  Radio,
  Monitor,
  Laptop,
  Tablet,
  Smartphone,
  Watch,
  Printer,
  HardDrive,
  Usb,
  Battery,
  Plug,
  Lightbulb,
  Fan,
  Thermometer,
  Umbrella,
  Cloud,
  Wind,
  Snowflake,
  Flame,
  Leaf,
  TreePine,
  Mountain,
  Waves,
  Anchor,
  Compass,
  Navigation,
  Truck,
  Bus,
  Bike,
  Ship,
  Rocket,
  Package,
  Box,
  Archive,
  Folder,
  File,
  Clipboard,
  Newspaper,
  BookOpen,
  GraduationCap,
  Award,
  Trophy,
  Medal,
  Target,
  Crosshair,
  Shield,
  Lock,
  Key,
  Eye,
  Search,
  Filter,
  Settings,
  Hammer,
  Scissors,
  Brush,
  Paintbrush,
  Palette,
  Pen,
  Pencil,
  Eraser,
  Ruler,
  Calculator,
  Percent,
  DollarSign,
  Euro,
  PoundSterling,
  Coins,
  Banknote,
  Receipt,
  Building2,
  Store,
  ShoppingBag,
  PartyPopper,
  Cake,
  Wine,
  Beer,
  Pizza,
  Apple,
  Carrot,
  Egg,
  Milk,
  Cookie,
  IceCream2,
  Candy,
  Cigarette,
  Pill,
  Stethoscope,
  Syringe,
  Activity,
  Dumbbell,
  PersonStanding,
  Users,
  User,
  UserPlus,
  UserMinus,
  Accessibility,
  Footprints,
  Glasses,
  Gem,
  Crown,
  Sparkles,
  Wand2,
  CircleDollarSign,
  HandCoins,
  BadgeDollarSign,
  Vault,
  Scale,
  Gavel,
  Scroll,
  FileCheck,
  FilePlus,
  FileMinus,
  FileX,
  FileQuestion,
  Files,
  FolderOpen,
  FolderPlus,
  FolderMinus,
  FolderX,
  Inbox,
  Send,
  Mail,
  MailOpen,
  MessageSquare,
  MessageCircle,
  PhoneCall,
  Video,
  VideoOff,
  MicOff,
  Volume,
  VolumeX,
  Volume1,
  Volume2,
  Play,
  Pause,
  Square,
  Circle,
  Triangle,
  Hexagon,
  Octagon,
  Pentagon,
  Diamond,
  HeartPulse,
  Smile,
  Frown,
  Meh,
  Angry,
  Laugh,
  ThumbsUp,
  ThumbsDown,
  Hand,
  Handshake,
} from 'lucide-react'

/**
 * Map of icon names to their components
 * @type {Object.<string, React.Component>}
 */
const iconMap = {
  // Category icons (from User.js defaults)
  briefcase: Briefcase,
  gift: Gift,
  arrowleft: ArrowLeft,
  pluscircle: PlusCircle,
  home: Home,
  zap: Zap,
  droplet: Droplet,
  wifi: Wifi,
  phone: Phone,
  fuel: Fuel,
  train: Train,
  wrench: Wrench,
  shoppingcart: ShoppingCart,
  utensils: Utensils,
  heart: Heart,
  music: Music,
  tv: Tv,
  shirt: Shirt,
  filetext: FileText,
  landmark: Landmark,
  morehorizontal: MoreHorizontal,
  arrowrightleft: ArrowRightLeft,
  piggybank: PiggyBank,
  // Common icons
  tag: Tag,
  wallet: Wallet,
  car: Car,
  creditcard: CreditCard,
  building: Building,
  plane: Plane,
  book: Book,
  coffee: Coffee,
  gamepad: Gamepad2,
  gamepad2: Gamepad2,
  baby: Baby,
  dog: Dog,
  cat: Cat,
  flower: Flower2,
  flower2: Flower2,
  sun: Sun,
  moon: Moon,
  star: Star,
  flag: Flag,
  bell: Bell,
  clock: Clock,
  calendar: Calendar,
  map: Map,
  globe: Globe,
  camera: Camera,
  image: Image,
  film: Film,
  headphones: Headphones,
  mic: Mic,
  speaker: Speaker,
  radio: Radio,
  monitor: Monitor,
  laptop: Laptop,
  tablet: Tablet,
  smartphone: Smartphone,
  watch: Watch,
  printer: Printer,
  harddrive: HardDrive,
  usb: Usb,
  battery: Battery,
  plug: Plug,
  lightbulb: Lightbulb,
  fan: Fan,
  thermometer: Thermometer,
  umbrella: Umbrella,
  cloud: Cloud,
  wind: Wind,
  snowflake: Snowflake,
  flame: Flame,
  leaf: Leaf,
  tree: TreePine,
  treepine: TreePine,
  mountain: Mountain,
  waves: Waves,
  anchor: Anchor,
  compass: Compass,
  navigation: Navigation,
  truck: Truck,
  bus: Bus,
  bike: Bike,
  ship: Ship,
  rocket: Rocket,
  package: Package,
  box: Box,
  archive: Archive,
  folder: Folder,
  file: File,
  clipboard: Clipboard,
  newspaper: Newspaper,
  bookopen: BookOpen,
  graduationcap: GraduationCap,
  award: Award,
  trophy: Trophy,
  medal: Medal,
  target: Target,
  crosshair: Crosshair,
  shield: Shield,
  lock: Lock,
  key: Key,
  eye: Eye,
  search: Search,
  filter: Filter,
  settings: Settings,
  hammer: Hammer,
  scissors: Scissors,
  brush: Brush,
  paintbrush: Paintbrush,
  palette: Palette,
  pen: Pen,
  pencil: Pencil,
  eraser: Eraser,
  ruler: Ruler,
  calculator: Calculator,
  percent: Percent,
  dollarsign: DollarSign,
  euro: Euro,
  poundsterling: PoundSterling,
  coins: Coins,
  banknote: Banknote,
  receipt: Receipt,
  building2: Building2,
  store: Store,
  shoppingbag: ShoppingBag,
  partypopper: PartyPopper,
  cake: Cake,
  wine: Wine,
  beer: Beer,
  pizza: Pizza,
  apple: Apple,
  carrot: Carrot,
  egg: Egg,
  milk: Milk,
  cookie: Cookie,
  icecream: IceCream2,
  icecream2: IceCream2,
  candy: Candy,
  cigarette: Cigarette,
  pill: Pill,
  stethoscope: Stethoscope,
  syringe: Syringe,
  activity: Activity,
  dumbbell: Dumbbell,
  personstanding: PersonStanding,
  users: Users,
  user: User,
  userplus: UserPlus,
  userminus: UserMinus,
  accessibility: Accessibility,
  footprints: Footprints,
  glasses: Glasses,
  gem: Gem,
  crown: Crown,
  sparkles: Sparkles,
  wand: Wand2,
  wand2: Wand2,
  circledollarsign: CircleDollarSign,
  handcoins: HandCoins,
  badgedollarsign: BadgeDollarSign,
  vault: Vault,
  scale: Scale,
  gavel: Gavel,
  scroll: Scroll,
  filecheck: FileCheck,
  fileplus: FilePlus,
  fileminus: FileMinus,
  filex: FileX,
  filequestion: FileQuestion,
  files: Files,
  folderopen: FolderOpen,
  folderplus: FolderPlus,
  folderminus: FolderMinus,
  folderx: FolderX,
  inbox: Inbox,
  send: Send,
  mail: Mail,
  mailopen: MailOpen,
  messagesquare: MessageSquare,
  messagecircle: MessageCircle,
  phonecall: PhoneCall,
  video: Video,
  videooff: VideoOff,
  micoff: MicOff,
  volume: Volume,
  volumex: VolumeX,
  volume1: Volume1,
  volume2: Volume2,
  play: Play,
  pause: Pause,
  square: Square,
  circle: Circle,
  triangle: Triangle,
  hexagon: Hexagon,
  octagon: Octagon,
  pentagon: Pentagon,
  diamond: Diamond,
  heartpulse: HeartPulse,
  smile: Smile,
  frown: Frown,
  meh: Meh,
  angry: Angry,
  laugh: Laugh,
  thumbsup: ThumbsUp,
  thumbsdown: ThumbsDown,
  hand: Hand,
  handshake: Handshake,
}

/**
 * Get an icon component by name
 * @param {string} iconName - Name of the icon (case-insensitive)
 * @returns {React.Component} The icon component or Tag as fallback
 */
export function getIconComponent(iconName) {
  if (!iconName) return Tag
  const normalizedName = iconName.toLowerCase().replace(/[^a-z0-9]/g, '')
  return iconMap[normalizedName] || Tag
}

export default iconMap
