import { z } from 'zod';

/**
 * Types de débit
 */
export const debitTypes = ['immediate', 'deferred'];

/**
 * Schéma de base pour carte de crédit
 */
const creditCardBaseSchema = z.object({
  accountId: z.string().uuid('ID de compte invalide'),
  linkedAccountId: z.string().uuid('ID de compte lié invalide').nullable().optional(),
  name: z.string().min(1, 'Nom requis').max(100, 'Nom trop long').trim(),
  cardNumberLast4: z.string().length(4).regex(/^\d{4}$/, 'Format invalide').optional(),
  expirationDate: z.string().regex(/^(0[1-9]|1[0-2])\/\d{2}$/, 'Format invalide (MM/AA)').nullable().optional(),
  debitType: z.enum(debitTypes, { errorMap: () => ({ message: 'Type de débit invalide' }) }),
  cycleStartDay: z.number().int().min(1).max(28).default(1),
  debitDay: z.number().int().min(1).max(28).nullable().optional(),
  debitDaysBeforeEnd: z.number().int().min(0).max(10).nullable().optional(),
  creditLimit: z.number().positive().nullable().optional(),
  hasDedicatedAccount: z.boolean().default(false),
  autoGenerateDebit: z.boolean().default(true),
  color: z.string().regex(/^#[0-9A-Fa-f]{6}$/).default('#EF4444'),
  notes: z.string().max(1000).optional(),
});

/**
 * Schéma de création de carte de crédit
 */
export const createCreditCardSchema = creditCardBaseSchema.refine((data) => {
  if (data.debitType === 'deferred') {
    return data.debitDay != null || data.debitDaysBeforeEnd != null;
  }
  return true;
}, { message: 'Pour le débit différé, spécifiez le jour de prélèvement ou J-X', path: ['debitDay'] });

/**
 * Schéma de mise à jour de carte de crédit
 */
export const updateCreditCardSchema = creditCardBaseSchema.omit({ accountId: true }).partial();

/**
 * Schéma de paramètres d'URL
 */
export const creditCardIdParamSchema = z.object({
  id: z.string().uuid('ID de carte invalide'),
});

/**
 * Schéma de requête pour les cycles
 */
export const listCyclesQuerySchema = z.object({
  status: z.enum(['open', 'pending', 'debited']).optional(),
  startDate: z.string().regex(/^\d{4}-\d{2}-\d{2}$/).optional(),
  endDate: z.string().regex(/^\d{4}-\d{2}-\d{2}$/).optional(),
  page: z.coerce.number().int().positive().default(1),
  limit: z.coerce.number().int().positive().max(50).default(12),
});
